/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/dictionary/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dictionary Terms
         * @description List governed dictionary terms with optional scope and status filtering.
         */
        get: operations["list_dictionary_terms_api_v1_dictionary_terms_get"];
        put?: never;
        /**
         * Create Dictionary Term
         * @description Propose a project- or organization-scoped dictionary term.
         */
        post: operations["create_dictionary_term_api_v1_dictionary_terms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictionary/terms/{term_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve Dictionary Term
         * @description Approve or reject a proposed dictionary term.
         */
        patch: operations["approve_dictionary_term_api_v1_dictionary_terms__term_id__approve_patch"];
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List documents visible to the current user.
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Persist a validated document and enqueue canonical extraction.
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Return safe metadata for one document.
         */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Audit Events
         * @description List immutable audit events for an audited document in chronological order.
         */
        get: operations["list_document_audit_events_api_v1_documents__document_id__audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Document Disposition
         * @description Apply final Lead Reviewer disposition to an audited document.
         */
        post: operations["set_document_disposition_api_v1_documents__document_id__disposition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Document Events
         * @description Stream real-time processing progress and stage transitions via Server-Sent Events (SSE).
         */
        get: operations["stream_document_events_api_v1_documents__document_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Document
         * @description Export the annotated rendition or structured issue log in PDF, XLSX, CSV, or JSON format.
         */
        get: operations["export_document_api_v1_documents__document_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Issues
         * @description List issues with optional canonical category filtering.
         */
        get: operations["list_document_issues_api_v1_documents__document_id__issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Pdf
         * @description Stream the canonical PDF rendition of an uploaded document.
         */
        get: operations["get_document_pdf_api_v1_documents__document_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Status
         * @description Return processing progress and latest stage states.
         */
        get: operations["get_document_status_api_v1_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/traceability-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Traceability Summary
         * @description Return traceability counts for audit triage.
         */
        get: operations["get_traceability_summary_api_v1_documents__document_id__traceability_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/bulk-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Decide Issues
         * @description Apply a decision to multiple issues, strictly prohibiting traceability bulk-accept.
         */
        post: operations["bulk_decide_issues_api_v1_issues_bulk_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Decide Issue
         * @description Apply an optimistically locked QA decision.
         */
        patch: operations["decide_issue_api_v1_issues__issue_id__decision_patch"];
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Dispose Issue
         * @description Append an optimistically locked Lead Reviewer disposition.
         */
        patch: operations["dispose_issue_api_v1_issues__issue_id__disposition_patch"];
        trace?: never;
    };
    "/api/v1/standards-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Standard Patterns
         * @description List configured standards-code patterns.
         */
        get: operations["list_standard_patterns_api_v1_standards_registry_get"];
        put?: never;
        /**
         * Create Standard Pattern
         * @description Register an organization-scoped standards-code pattern.
         */
        post: operations["create_standard_pattern_api_v1_standards_registry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditEventListResponse
         * @description Collection of immutable audit events for a document.
         */
        AuditEventListResponse: {
            /** Events */
            events: components["schemas"]["AuditEventRead"][];
            /** Total */
            total: number;
        };
        /**
         * AuditEventRead
         * @description Immutable audit event record consumed by review and compliance interfaces.
         */
        AuditEventRead: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Role */
            actor_role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Issue Id */
            issue_id?: string | null;
            /** New State */
            new_state: {
                [key: string]: unknown;
            };
            /** Notes */
            notes?: string | null;
            /** Previous State */
            previous_state?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /**
             * File
             * @description Native-text PDF or DOCX
             */
            file: string;
        };
        /**
         * BoundingBox
         * @description PDF-point rectangle in the canonical top-left coordinate system.
         */
        BoundingBox: {
            /** Page Height */
            page_height: number;
            /** Page Index */
            page_index: number;
            /** Page Width */
            page_width: number;
            /** X0 */
            x0: number;
            /** X1 */
            x1: number;
            /** Y0 */
            y0: number;
            /** Y1 */
            y1: number;
        };
        /**
         * BulkDecisionRequest
         * @description Bulk decision applied across multiple eligible findings.
         */
        BulkDecisionRequest: {
            /**
             * Actor Id
             * @default reviewer@local
             */
            actor_id: string;
            /**
             * Actor Role
             * @default QA_ENGINEER
             */
            actor_role: string;
            /** Comment */
            comment?: string | null;
            decision: components["schemas"]["Decision"];
            /** Issue Ids */
            issue_ids: string[];
        };
        /**
         * BulkDecisionResponse
         * @description Outcome of an authorized bulk decision operation.
         */
        BulkDecisionResponse: {
            decision: components["schemas"]["Decision"];
            /** Updated Count */
            updated_count: number;
            /** Updated Issue Ids */
            updated_issue_ids: string[];
        };
        /**
         * Decision
         * @description QA decision applied to a detected issue.
         * @enum {string}
         */
        Decision: "ACCEPTED" | "REJECTED" | "EDITED" | "FLAGGED";
        /**
         * DictionaryTermApprovalRequest
         * @description Admin approval or rejection of a proposed term.
         */
        DictionaryTermApprovalRequest: {
            /** Comment */
            comment?: string | null;
            status: components["schemas"]["DictionaryTermStatus"];
        };
        /**
         * DictionaryTermCreate
         * @description Request to propose a term for a project or organization.
         */
        DictionaryTermCreate: {
            /** Rationale */
            rationale?: string | null;
            /** Scope */
            scope: string;
            /** Term */
            term: string;
        };
        /**
         * DictionaryTermListResponse
         * @description Paginated dictionary collection.
         */
        DictionaryTermListResponse: {
            pagination: components["schemas"]["PageInfo"];
            /** Terms */
            terms: components["schemas"]["DictionaryTermRead"][];
        };
        /**
         * DictionaryTermRead
         * @description Governed dictionary entry.
         */
        DictionaryTermRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scope */
            scope: string;
            status: components["schemas"]["DictionaryTermStatus"];
            /** Term */
            term: string;
        };
        /**
         * DictionaryTermStatus
         * @description Governance state for a proposed dictionary term.
         * @enum {string}
         */
        DictionaryTermStatus: "PROPOSED" | "APPROVED" | "REJECTED";
        /**
         * Disposition
         * @description Lead Reviewer disposition for audit-sensitive findings.
         * @enum {string}
         */
        Disposition: "JUSTIFIED_EXCEPTION" | "REQUIRES_CORRECTION";
        /**
         * DocumentDispositionRequest
         * @description Lead Reviewer final document-level sign-off.
         */
        DocumentDispositionRequest: {
            /**
             * Actor Id
             * @default reviewer@local
             */
            actor_id: string;
            /**
             * Actor Role
             * @default LEAD_REVIEWER
             */
            actor_role: string;
            disposition: components["schemas"]["ReviewStatus"];
            /** Justification */
            justification: string;
        };
        /**
         * DocumentListResponse
         * @description Paginated document collection.
         */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentRead"][];
            pagination: components["schemas"]["PageInfo"];
        };
        /**
         * DocumentRead
         * @description Safe document metadata returned to clients.
         */
        DocumentRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Media Type */
            media_type: string;
            /** Page Count */
            page_count?: number | null;
            /** Progress Pct */
            progress_pct: number;
            review_status: components["schemas"]["ReviewStatus"];
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentStatus
         * @description Processing lifecycle for an uploaded document.
         * @enum {string}
         */
        DocumentStatus: "QUEUED" | "PROCESSING" | "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "FAILED";
        /**
         * DocumentStatusResponse
         * @description Processing and stage status used for polling.
         */
        DocumentStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress Pct */
            progress_pct: number;
            review_status: components["schemas"]["ReviewStatus"];
            /** Stages */
            stages: components["schemas"]["StageRunRead"][];
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentUploadResponse
         * @description Response after a valid upload is persisted and queued.
         * @example {
         *       "created_at": "2026-09-04T04:00:00Z",
         *       "deduplicated": false,
         *       "filename": "Inspection_Report_Rev-A.pdf",
         *       "id": "ed846165-102f-49f9-9fd0-f25c0d4cfe6e",
         *       "status": "QUEUED"
         *     }
         */
        DocumentUploadResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * FieldViolation
         * @description One request-validation failure safe to expose to an API client.
         */
        FieldViolation: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IssueCategory
         * @description Top-level issue grouping used by API filters and the review UI.
         * @enum {string}
         */
        IssueCategory: "LINGUISTIC" | "TRACEABILITY" | "SYSTEM";
        /**
         * IssueDecisionRequest
         * @description Optimistically locked QA decision mutation.
         */
        IssueDecisionRequest: {
            /**
             * Actor Id
             * @default reviewer@local
             */
            actor_id: string;
            /**
             * Actor Role
             * @default QA_ENGINEER
             */
            actor_role: string;
            /** Comment */
            comment?: string | null;
            decision: components["schemas"]["Decision"];
            /** Edited Value */
            edited_value?: string | null;
            /** Expected Version */
            expected_version: number;
        };
        /**
         * IssueDispositionRequest
         * @description Optimistically locked Lead Reviewer disposition mutation.
         */
        IssueDispositionRequest: {
            /**
             * Actor Id
             * @default reviewer@local
             */
            actor_id: string;
            /**
             * Actor Role
             * @default LEAD_REVIEWER
             */
            actor_role: string;
            disposition: components["schemas"]["Disposition"];
            /** Expected Version */
            expected_version: number;
            /** Justification */
            justification: string;
        };
        /**
         * IssueListResponse
         * @description Paginated issue collection plus review summary counts.
         */
        IssueListResponse: {
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Issues */
            issues: components["schemas"]["IssueRead"][];
            pagination: components["schemas"]["PageInfo"];
        };
        /**
         * IssueRead
         * @description Unified issue record consumed by the review UI.
         */
        IssueRead: {
            category: components["schemas"]["IssueCategory"];
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            decision?: components["schemas"]["Decision"] | null;
            /** Decision By */
            decision_by?: string | null;
            /** Decision Comment */
            decision_comment?: string | null;
            disposition?: components["schemas"]["Disposition"] | null;
            /** Disposition By */
            disposition_by?: string | null;
            /** Disposition Justification */
            disposition_justification?: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Evidence */
            evidence: components["schemas"]["TableMathEvidence"] | components["schemas"]["ReferenceDriftEvidence"] | components["schemas"]["RevisionEvidence"] | components["schemas"]["StandardEvidence"] | components["schemas"]["LinguisticEvidence"] | components["schemas"]["StageFailureEvidence"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Message */
            message: string;
            severity: components["schemas"]["Severity"];
            /** Type */
            type: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Version */
            version: number;
        };
        /**
         * LinguisticEvidence
         * @description Original span and optional replacement for language findings.
         */
        LinguisticEvidence: {
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LINGUISTIC";
            /** Location */
            location: components["schemas"]["BoundingBox"] | components["schemas"]["TextSpan"];
            original_location?: components["schemas"]["BoundingBox"] | null;
            /** Original Text */
            original_text: string;
            /** Rule Version */
            rule_version: string;
            /** Suggestion */
            suggestion?: string | null;
        };
        /**
         * PageInfo
         * @description Cursor-free pagination metadata for the initial API contract.
         */
        PageInfo: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ProblemDetail
         * @description RFC 9457-style error response with a stable application code.
         * @example {
         *       "code": "FEATURE_NOT_READY",
         *       "detail": "Document upload is not implemented yet.",
         *       "errors": [],
         *       "instance": "/api/v1/documents/upload",
         *       "status": 501,
         *       "title": "Feature not ready",
         *       "type": "urn:docqc:error:FEATURE_NOT_READY"
         *     }
         */
        ProblemDetail: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldViolation"][];
            /** Instance */
            instance?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * ReferenceDriftEvidence
         * @description Referenced and actual page evidence for ToC/LoF/LoT drift.
         */
        ReferenceDriftEvidence: {
            /** Actual Page Label */
            actual_page_label: string;
            entry_location: components["schemas"]["BoundingBox"];
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "REFERENCE_DRIFT";
            /** Label */
            label: string;
            /** Page Delta */
            page_delta: number;
            /** Referenced Page Label */
            referenced_page_label: string;
            /** Rule Version */
            rule_version: string;
            target_location: components["schemas"]["BoundingBox"];
        };
        /**
         * ReviewStatus
         * @description Human review lifecycle, kept separate from processing status.
         * @enum {string}
         */
        ReviewStatus: "PENDING" | "IN_REVIEW" | "APPROVED" | "REVISION_REQUIRED";
        /**
         * RevisionEvidence
         * @description Three-way filename, cover, and revision-history evidence.
         */
        RevisionEvidence: {
            /** Cover Revision */
            cover_revision: string | null;
            /** Extractor Version */
            extractor_version: string;
            /** Filename Revision */
            filename_revision: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "REVISION";
            /** Locations */
            locations: components["schemas"]["BoundingBox"][];
            /** Revision Sheet Revision */
            revision_sheet_revision: string | null;
            /** Rule Version */
            rule_version: string;
            /** Sources Disagreeing */
            sources_disagreeing: ("FILENAME" | "COVER" | "REVISION_SHEET")[];
        };
        /**
         * Severity
         * @description Ordered human-facing issue severity labels.
         * @enum {string}
         */
        Severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
        /**
         * StageFailureEvidence
         * @description Sanitized pipeline-stage failure surfaced without losing other results.
         */
        StageFailureEvidence: {
            /** Error Code */
            error_code: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "STAGE_FAILURE";
            /** Retryable */
            retryable: boolean;
            /** Rule Version */
            rule_version: string;
            /** Stage */
            stage: string;
        };
        /**
         * StageRunRead
         * @description Latest observable state for one pipeline stage execution.
         */
        StageRunRead: {
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Progress Pct */
            progress_pct: number;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["StageStatus"];
        };
        /**
         * StageStatus
         * @description Lifecycle of one versioned pipeline stage run.
         * @enum {string}
         */
        StageStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "SUCCEEDED_WITH_WARNINGS" | "FAILED" | "SKIPPED";
        /**
         * StandardEvidence
         * @description Normalized body citation and bibliography evidence.
         */
        StandardEvidence: {
            /** Bibliography Edition Year */
            bibliography_edition_year?: number | null;
            /** Bibliography Entry */
            bibliography_entry?: string | null;
            bibliography_location?: components["schemas"]["BoundingBox"] | null;
            /** Body Edition Year */
            body_edition_year?: number | null;
            body_location: components["schemas"]["BoundingBox"];
            /** Cited Standard */
            cited_standard: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "STANDARD";
            /** Rule Version */
            rule_version: string;
        };
        /**
         * StandardPatternCreate
         * @description Admin request to register a normalized standards-code pattern.
         */
        StandardPatternCreate: {
            /** Code Family */
            code_family: string;
            /** Code Pattern */
            code_pattern: string;
            /** Description */
            description: string;
            /** Organization Scope */
            organization_scope: string;
        };
        /**
         * StandardPatternListResponse
         * @description Paginated standards-registry collection.
         */
        StandardPatternListResponse: {
            pagination: components["schemas"]["PageInfo"];
            /** Standards */
            standards: components["schemas"]["StandardPatternRead"][];
        };
        /**
         * StandardPatternRead
         * @description Persisted standards-registry entry.
         */
        StandardPatternRead: {
            /** Code Family */
            code_family: string;
            /** Code Pattern */
            code_pattern: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Organization Scope */
            organization_scope: string;
        };
        /**
         * TableMathEvidence
         * @description Arithmetic operands and locations supporting a table finding.
         */
        TableMathEvidence: {
            /** Computed Value */
            computed_value: string;
            /** Delta */
            delta: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "TABLE_MATH";
            /** Operand Locations */
            operand_locations: components["schemas"]["BoundingBox"][];
            /** Rule Version */
            rule_version: string;
            /** Stated Value */
            stated_value: string;
            /** Tolerance */
            tolerance: string;
            total_location: components["schemas"]["BoundingBox"];
        };
        /**
         * TextSpan
         * @description Character offsets within normalized extracted page text.
         */
        TextSpan: {
            /** End */
            end: number;
            /** Page Index */
            page_index: number;
            /** Start */
            start: number;
        };
        /**
         * TraceabilitySummaryResponse
         * @description Counts required by the audit-focused dashboard.
         */
        TraceabilitySummaryResponse: {
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Counts By Type */
            counts_by_type: {
                [key: string]: number;
            };
            /** Critical Count */
            critical_count: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Unresolved Count */
            unresolved_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_dictionary_terms_api_v1_dictionary_terms_get: {
        parameters: {
            query?: {
                scope?: string | null;
                status?: components["schemas"]["DictionaryTermStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryTermListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dictionary_term_api_v1_dictionary_terms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryTermCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryTermRead"];
                };
            };
            /** @description Dictionary term not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Term already exists for the given scope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_dictionary_term_api_v1_dictionary_terms__term_id__approve_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryTermApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryTermRead"];
                };
            };
            /** @description Dictionary term not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Term already exists for the given scope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    list_document_audit_events_api_v1_documents__document_id__audit_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventListResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_document_disposition_api_v1_documents__document_id__disposition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentDispositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_document_events_api_v1_documents__document_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_api_v1_documents__document_id__export_get: {
        parameters: {
            query: {
                format: string;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_issues_api_v1_documents__document_id__issues_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["IssueCategory"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_document_pdf_api_v1_documents__document_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document or canonical PDF not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_status_api_v1_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_traceability_summary_api_v1_documents__document_id__traceability_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceabilitySummaryResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_decide_issues_api_v1_issues_bulk_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkDecisionResponse"];
                };
            };
            /** @description Traceability bulk accept prohibited */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    decide_issue_api_v1_issues__issue_id__decision_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispose_issue_api_v1_issues__issue_id__disposition_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueDispositionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            /** @description Issue not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Optimistic concurrency conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_standard_patterns_api_v1_standards_registry_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardPatternListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_standard_pattern_api_v1_standards_registry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardPatternCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardPatternRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
