/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the password for the authenticated account owner.
         */
        post: operations["change_password_api_v1_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate an active user and issue a JWT.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear the browser session cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Profile
         * @description Update the authenticated user's profile fields.
         */
        patch: operations["update_profile_api_v1_auth_me_patch"];
        trace?: never;
    };
    "/api/v1/auth/register-engineer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Engineer
         * @description Allow only lead engineers to create engineer accounts.
         */
        post: operations["register_engineer_api_v1_auth_register_engineer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description List all accounts for the lead/superuser administration console.
         */
        get: operations["list_users_api_v1_auth_users_get"];
        put?: never;
        /**
         * Create User
         * @description Create an engineer or lead account with a temporary password.
         */
        post: operations["create_user_api_v1_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset User Password
         * @description Replace an account password without exposing its hash.
         */
        post: operations["reset_user_password_api_v1_auth_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User Status
         * @description Activate or deactivate an account.
         */
        patch: operations["update_user_status_api_v1_auth_users__user_id__status_patch"];
        trace?: never;
    };
    "/api/v1/dictionary/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Dictionary Terms
         * @description List governed dictionary terms with optional scope and status filtering.
         */
        get: operations["list_dictionary_terms_api_v1_dictionary_terms_get"];
        put?: never;
        /**
         * Create Dictionary Term
         * @description Propose a project- or organization-scoped dictionary term.
         */
        post: operations["create_dictionary_term_api_v1_dictionary_terms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dictionary/terms/{term_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Approve Dictionary Term
         * @description Approve or reject a proposed dictionary term.
         */
        patch: operations["approve_dictionary_term_api_v1_dictionary_terms__term_id__approve_patch"];
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List documents visible to the current user.
         */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Persist a validated document and enqueue canonical extraction.
         */
        post: operations["upload_document_api_v1_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document
         * @description Return safe metadata for one document.
         */
        get: operations["get_document_api_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Permanently delete a document, its database records, storage files, and artifacts.
         */
        delete: operations["delete_document_api_v1_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Document Events
         * @description Stream real-time processing progress and stage transitions via Server-Sent Events (SSE).
         */
        get: operations["stream_document_events_api_v1_documents__document_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Document
         * @description Export the annotated original PDF or formal DOCX review report.
         */
        get: operations["export_document_api_v1_documents__document_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Issues
         * @description List issues with optional canonical category filtering.
         */
        get: operations["list_document_issues_api_v1_documents__document_id__issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/mark-reviewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Document Reviewed
         * @description Mark an owned document as reviewed by its engineer owner.
         */
        post: operations["mark_document_reviewed_api_v1_documents__document_id__mark_reviewed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Pdf
         * @description Stream the canonical PDF rendition of an uploaded document.
         */
        get: operations["get_document_pdf_api_v1_documents__document_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Preview
         * @description Return the current draft-report composition without generating a file.
         */
        get: operations["get_report_preview_api_v1_documents__document_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/request-revision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Document Revision
         * @description Return a document to an engineer for revision.
         */
        post: operations["request_document_revision_api_v1_documents__document_id__request_revision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Status
         * @description Return processing progress and latest stage states.
         */
        get: operations["get_document_status_api_v1_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/traceability-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Traceability Summary
         * @description Return traceability counts for audit triage.
         */
        get: operations["get_traceability_summary_api_v1_documents__document_id__traceability_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Document
         * @description Verify a document as a lead engineer.
         */
        post: operations["verify_document_api_v1_documents__document_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/issues/{issue_id}/curation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Curate Issue
         * @description Include/exclude a finding from the generated report and attach a note.
         */
        patch: operations["curate_issue_api_v1_issues__issue_id__curation_patch"];
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List projects visible to the authenticated user.
         */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a project for lead users.
         */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Assign Project
         * @description Assign or unassign a project to an active user.
         */
        patch: operations["assign_project_api_v1_projects__project_id__assign_patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Project Documents
         * @description List project documents with lead-only cross-engineer filters.
         */
        get: operations["list_project_documents_api_v1_projects__project_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Project Document
         * @description Upload a document and assign its project and owner.
         */
        post: operations["upload_project_document_api_v1_projects__project_id__documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/standards-registry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Standard Patterns
         * @description List configured standards-code patterns.
         */
        get: operations["list_standard_patterns_api_v1_standards_registry_get"];
        put?: never;
        /**
         * Create Standard Pattern
         * @description Register an organization-scoped standards-code pattern.
         */
        post: operations["create_standard_pattern_api_v1_standards_registry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_documents_upload_post */
        Body_upload_document_api_v1_documents_upload_post: {
            /**
             * File
             * @description Native-text PDF or DOCX
             */
            file: string;
        };
        /** Body_upload_project_document_api_v1_projects__project_id__documents_upload_post */
        Body_upload_project_document_api_v1_projects__project_id__documents_upload_post: {
            /**
             * File
             * @description Native-text PDF or DOCX
             */
            file: string;
        };
        /**
         * BoundingBox
         * @description PDF-point rectangle in the canonical top-left coordinate system.
         */
        BoundingBox: {
            /** Page Height */
            page_height: number;
            /** Page Index */
            page_index: number;
            /** Page Width */
            page_width: number;
            /** X0 */
            x0: number;
            /** X1 */
            x1: number;
            /** Y0 */
            y0: number;
            /** Y1 */
            y1: number;
        };
        /**
         * BudinskiEvidence
         * @description Technical writing rules, 4 baselines, and Appendix 12 checklist evidence.
         */
        BudinskiEvidence: {
            bounding_box?: components["schemas"]["BoundingBox"] | null;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "BUDINSKI";
            /** Measure */
            measure?: string | null;
            /** Rule Number */
            rule_number?: string | null;
            /** Rule Version */
            rule_version: string;
            /** What Body Has */
            what_body_has?: string | null;
            /** What It Says */
            what_it_says?: string | null;
            /** What Would Fix It */
            what_would_fix_it?: string | null;
            /** Where Location */
            where_location?: string | null;
            /** Why It Matters */
            why_it_matters?: string | null;
        };
        /**
         * CategoryBandEvidence
         * @description Evidence for a categorical numeric-band contradiction.
         */
        CategoryBandEvidence: {
            /** Category Id */
            category_id?: string | null;
            /** Extractor Version */
            extractor_version: string;
            /** Interval */
            interval?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "CATEGORY_BAND";
            /** Rule Version */
            rule_version: string;
            /** What Body Has */
            what_body_has?: string | null;
            /** What It Says */
            what_it_says: string;
            /** What Would Fix It */
            what_would_fix_it: string;
            /** Where */
            where: string;
            /** Why It Matters */
            why_it_matters: string;
        };
        /**
         * ChangePasswordRequest
         * @description Password replacement requested by the authenticated account owner.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /**
         * DictionaryTermApprovalRequest
         * @description Admin approval or rejection of a proposed term.
         */
        DictionaryTermApprovalRequest: {
            /** Comment */
            comment?: string | null;
            status: components["schemas"]["DictionaryTermStatus"];
        };
        /**
         * DictionaryTermCreate
         * @description Request to propose a term for a project or organization.
         */
        DictionaryTermCreate: {
            /** Rationale */
            rationale?: string | null;
            /** Scope */
            scope: string;
            /** Term */
            term: string;
        };
        /**
         * DictionaryTermListResponse
         * @description Paginated dictionary collection.
         */
        DictionaryTermListResponse: {
            pagination: components["schemas"]["PageInfo"];
            /** Terms */
            terms: components["schemas"]["DictionaryTermRead"][];
        };
        /**
         * DictionaryTermRead
         * @description Governed dictionary entry.
         */
        DictionaryTermRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scope */
            scope: string;
            status: components["schemas"]["DictionaryTermStatus"];
            /** Term */
            term: string;
        };
        /**
         * DictionaryTermStatus
         * @description Governance state for a proposed dictionary term.
         * @enum {string}
         */
        DictionaryTermStatus: "PROPOSED" | "APPROVED" | "REJECTED";
        /**
         * DocumentListResponse
         * @description Paginated document collection.
         */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentRead"][];
            pagination: components["schemas"]["PageInfo"];
        };
        /**
         * DocumentRead
         * @description Safe document metadata returned to clients.
         */
        DocumentRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Media Type */
            media_type: string;
            /** Owner Id */
            owner_id?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Page Count */
            page_count?: number | null;
            /** Progress Pct */
            progress_pct: number;
            /** Project Id */
            project_id?: string | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Verification Notes */
            verification_notes?: string | null;
            /** Verified At */
            verified_at?: string | null;
            /** Verified By Id */
            verified_by_id?: string | null;
            workflow_status: components["schemas"]["DocumentWorkflowStatus"];
        };
        /**
         * DocumentStatus
         * @description Processing lifecycle for an uploaded document.
         * @enum {string}
         */
        DocumentStatus: "QUEUED" | "PROCESSING" | "COMPLETED" | "COMPLETED_WITH_WARNINGS" | "FAILED";
        /**
         * DocumentStatusResponse
         * @description Processing and stage status used for polling.
         */
        DocumentStatusResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Progress Pct */
            progress_pct: number;
            /** Stages */
            stages: components["schemas"]["StageRunRead"][];
            status: components["schemas"]["DocumentStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DocumentUploadResponse
         * @description Response after a valid upload is persisted and queued.
         * @example {
         *       "created_at": "2026-09-04T04:00:00Z",
         *       "deduplicated": false,
         *       "filename": "Inspection_Report_Rev-A.pdf",
         *       "id": "ed846165-102f-49f9-9fd0-f25c0d4cfe6e",
         *       "status": "QUEUED"
         *     }
         */
        DocumentUploadResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Filename */
            filename: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["DocumentStatus"];
        };
        /**
         * DocumentWorkflowStatus
         * @description Human review lifecycle for a document.
         * @enum {string}
         */
        DocumentWorkflowStatus: "ANALYZING" | "REVIEWED_BY_ENGINEER" | "VERIFIED_BY_LEAD";
        /**
         * DocumentWorkflowUpdate
         * @description Payload for assigning a document and changing its review workflow.
         */
        DocumentWorkflowUpdate: {
            /** Owner Id */
            owner_id?: string | null;
            /** Project Id */
            project_id?: string | null;
            /** Verification Notes */
            verification_notes?: string | null;
            /** Verified By Id */
            verified_by_id?: string | null;
            workflow_status?: components["schemas"]["DocumentWorkflowStatus"] | null;
        };
        /**
         * FieldViolation
         * @description One request-validation failure safe to expose to an API client.
         */
        FieldViolation: {
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IssueCategory
         * @description Top-level issue grouping used by API filters and the review UI.
         * @enum {string}
         */
        IssueCategory: "LINGUISTIC" | "TRACEABILITY" | "SYSTEM" | "LAYOUT" | "BUDINSKI" | "SPELLING" | "GRAMMAR" | "DICTIONARY" | "STANDARD_TRACEABILITY";
        /**
         * IssueCurationRequest
         * @description Lightweight report curation; it is not an approval decision.
         */
        IssueCurationRequest: {
            /** Included In Report */
            included_in_report: boolean;
            /** Reviewer Note */
            reviewer_note?: string | null;
        };
        /**
         * IssueListResponse
         * @description Paginated issue collection plus review summary counts.
         */
        IssueListResponse: {
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Issues */
            issues: components["schemas"]["IssueRead"][];
            pagination: components["schemas"]["PageInfo"];
        };
        /**
         * IssueRead
         * @description Unified issue record consumed by the review UI.
         */
        IssueRead: {
            category: components["schemas"]["IssueCategory"];
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Evidence */
            evidence: components["schemas"]["TableMathEvidence"] | components["schemas"]["ReferenceDriftEvidence"] | components["schemas"]["RevisionEvidence"] | components["schemas"]["StandardEvidence"] | components["schemas"]["LinguisticEvidence"] | components["schemas"]["StageFailureEvidence"] | components["schemas"]["ReferenceRuleEvidence"] | components["schemas"]["LayoutEvidence"] | components["schemas"]["BudinskiEvidence"] | components["schemas"]["CategoryBandEvidence"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Included In Report
             * @default true
             */
            included_in_report: boolean;
            /** Message */
            message: string;
            /** Reviewer Note */
            reviewer_note?: string | null;
            severity: components["schemas"]["Severity"];
            /** Type */
            type: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /**
         * LayoutEvidence
         * @description Layout, whitespace, typography, and page continuity evidence.
         */
        LayoutEvidence: {
            /** Anomaly Type */
            anomaly_type: string;
            bounding_box?: components["schemas"]["BoundingBox"] | null;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LAYOUT";
            /** Page Index */
            page_index: number;
            /** Rule Version */
            rule_version: string;
            /** Snippet */
            snippet?: string | null;
            /** Suggested Fix */
            suggested_fix?: string | null;
        };
        /**
         * LinguisticEvidence
         * @description Original span and optional replacement for language findings.
         */
        LinguisticEvidence: {
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "LINGUISTIC";
            /** Location */
            location: components["schemas"]["BoundingBox"] | components["schemas"]["TextSpan"];
            original_location?: components["schemas"]["BoundingBox"] | null;
            /** Original Text */
            original_text: string;
            /** Rule Version */
            rule_version: string;
            /** Suggestion */
            suggestion?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * ManagedUserCreate
         * @description Payload for creating an engineer or lead account.
         */
        ManagedUserCreate: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Role
             * @default ENGINEER
             * @enum {string}
             */
            role: "ENGINEER" | "LEAD_ENGINEER";
            /** Temporary Password */
            temporary_password: string;
        };
        /**
         * PageInfo
         * @description Cursor-free pagination metadata for the initial API contract.
         */
        PageInfo: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * ProblemDetail
         * @description RFC 9457-style error response with a stable application code.
         * @example {
         *       "code": "FEATURE_NOT_READY",
         *       "detail": "Document upload is not implemented yet.",
         *       "errors": [],
         *       "instance": "/api/v1/documents/upload",
         *       "status": 501,
         *       "title": "Feature not ready",
         *       "type": "urn:docqc:error:FEATURE_NOT_READY"
         *     }
         */
        ProblemDetail: {
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldViolation"][];
            /** Instance */
            instance?: string | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * ProjectAssignment
         * @description Payload used by leads to assign a project to an engineer.
         */
        ProjectAssignment: {
            /** Assigned To Id */
            assigned_to_id?: string | null;
        };
        /**
         * ProjectCreate
         * @description Payload for creating a project.
         */
        ProjectCreate: {
            /** Code */
            code?: string | null;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Plant Area */
            plant_area?: string | null;
        };
        /**
         * ProjectRead
         * @description Project representation returned by the API.
         */
        ProjectRead: {
            /** Assigned To Id */
            assigned_to_id?: string | null;
            /** Assigned To Name */
            assigned_to_name?: string | null;
            /** Code */
            code?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By Id
             * Format: uuid
             */
            created_by_id: string;
            /** Created By Name */
            created_by_name?: string | null;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Plant Area */
            plant_area?: string | null;
            /**
             * Status
             * @default NO_DOCUMENTS
             */
            status: string;
            /**
             * Total Documents
             * @default 0
             */
            total_documents: number;
        };
        /**
         * ReferenceDriftEvidence
         * @description Referenced and actual page evidence for ToC/LoF/LoT drift.
         */
        ReferenceDriftEvidence: {
            /** Actual Page Label */
            actual_page_label: string;
            entry_location: components["schemas"]["BoundingBox"];
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "REFERENCE_DRIFT";
            /** Label */
            label: string;
            /** Page Delta */
            page_delta: number;
            /** Referenced Page Label */
            referenced_page_label: string;
            /** Rule Version */
            rule_version: string;
            target_location: components["schemas"]["BoundingBox"];
        };
        /**
         * ReferenceRuleEvidence
         * @description Provenance and parameters for reference standard rule findings.
         */
        ReferenceRuleEvidence: {
            /** Clause */
            clause: string;
            /**
             * Compliance Status
             * @default NON_COMPLIANT
             */
            compliance_status: string;
            /** Detected Parameter */
            detected_parameter?: string | null;
            /** Detected Value */
            detected_value?: string | null;
            /** Edition */
            edition: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "REFERENCE_RULE";
            location: components["schemas"]["BoundingBox"];
            /** Rule Kind */
            rule_kind: string;
            /** Rule Version */
            rule_version: string;
            /** Standard */
            standard: string;
            /** Standard Page */
            standard_page: number;
        };
        /** RegisterEngineerRequest */
        RegisterEngineerRequest: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /**
         * ReviewReportPreview
         * @description Summary used by the report-first review screen.
         */
        ReviewReportPreview: {
            /** Blockers */
            blockers: number;
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Included Findings */
            included_findings: number;
            /** Summary Judgement */
            summary_judgement: string;
        };
        /**
         * RevisionEvidence
         * @description Three-way filename, cover, and revision-history evidence.
         */
        RevisionEvidence: {
            /** Cover Revision */
            cover_revision: string | null;
            /** Extractor Version */
            extractor_version: string;
            /** Filename Revision */
            filename_revision: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "REVISION";
            /** Locations */
            locations: components["schemas"]["BoundingBox"][];
            /** Revision Sheet Revision */
            revision_sheet_revision: string | null;
            /** Rule Version */
            rule_version: string;
            /** Sources Disagreeing */
            sources_disagreeing: ("FILENAME" | "COVER" | "REVISION_SHEET")[];
        };
        /**
         * Severity
         * @description Ordered human-facing issue severity labels.
         * @enum {string}
         */
        Severity: "BLOCKER" | "CRITICAL" | "MAJOR" | "MINOR" | "INFO" | "HIGH" | "MEDIUM" | "LOW";
        /**
         * StageFailureEvidence
         * @description Sanitized pipeline-stage failure surfaced without losing other results.
         */
        StageFailureEvidence: {
            /** Error Code */
            error_code: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "STAGE_FAILURE";
            /** Retryable */
            retryable: boolean;
            /** Rule Version */
            rule_version: string;
            /** Stage */
            stage: string;
        };
        /**
         * StageRunRead
         * @description Latest observable state for one pipeline stage execution.
         */
        StageRunRead: {
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Name
             * @enum {string}
             */
            name: "EXTRACTING" | "LAYOUT_INSPECTION" | "BUDINSKI_AUDIT" | "STANDARDS_CHECK" | "LINGUISTIC_CHECK" | "AGGREGATING";
            /** Progress Pct */
            progress_pct: number;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["StageStatus"];
        };
        /**
         * StageStatus
         * @description Lifecycle of one versioned pipeline stage run.
         * @enum {string}
         */
        StageStatus: "PENDING" | "RUNNING" | "SUCCEEDED" | "SUCCEEDED_WITH_WARNINGS" | "FAILED" | "SKIPPED";
        /**
         * StandardEvidence
         * @description Normalized body citation and bibliography evidence.
         */
        StandardEvidence: {
            /** Bibliography Edition Year */
            bibliography_edition_year?: number | null;
            /** Bibliography Entry */
            bibliography_entry?: string | null;
            bibliography_location?: components["schemas"]["BoundingBox"] | null;
            /** Body Edition Year */
            body_edition_year?: number | null;
            body_location: components["schemas"]["BoundingBox"];
            /** Cited Standard */
            cited_standard: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "STANDARD";
            /** Rule Version */
            rule_version: string;
        };
        /**
         * StandardPatternCreate
         * @description Admin request to register a normalized standards-code pattern.
         */
        StandardPatternCreate: {
            /** Code Family */
            code_family: string;
            /** Code Pattern */
            code_pattern: string;
            /** Description */
            description: string;
            /** Organization Scope */
            organization_scope: string;
        };
        /**
         * StandardPatternListResponse
         * @description Paginated standards-registry collection.
         */
        StandardPatternListResponse: {
            pagination: components["schemas"]["PageInfo"];
            /** Standards */
            standards: components["schemas"]["StandardPatternRead"][];
        };
        /**
         * StandardPatternRead
         * @description Persisted standards-registry entry.
         */
        StandardPatternRead: {
            /** Code Family */
            code_family: string;
            /** Code Pattern */
            code_pattern: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Organization Scope */
            organization_scope: string;
        };
        /**
         * TableMathEvidence
         * @description Arithmetic operands and locations supporting a table finding.
         */
        TableMathEvidence: {
            /** Computed Value */
            computed_value: string;
            /** Delta */
            delta: string;
            /** Extractor Version */
            extractor_version: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "TABLE_MATH";
            /** Operand Locations */
            operand_locations: components["schemas"]["BoundingBox"][];
            /** Rule Version */
            rule_version: string;
            /** Stated Value */
            stated_value: string;
            /** Tolerance */
            tolerance: string;
            total_location: components["schemas"]["BoundingBox"];
        };
        /**
         * TextSpan
         * @description Character offsets within normalized extracted page text.
         */
        TextSpan: {
            /** End */
            end: number;
            /** Page Index */
            page_index: number;
            /** Start */
            start: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /**
         * TraceabilitySummaryResponse
         * @description Counts required by the audit-focused dashboard.
         */
        TraceabilitySummaryResponse: {
            /** Counts By Severity */
            counts_by_severity: {
                [key: string]: number;
            };
            /** Counts By Type */
            counts_by_type: {
                [key: string]: number;
            };
            /** Critical Count */
            critical_count: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Unresolved Count */
            unresolved_count: number;
        };
        /**
         * UserManagementRead
         * @description User representation used by the lead user-management console.
         */
        UserManagementRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
            /**
             * Total Documents Owned
             * @default 0
             */
            total_documents_owned: number;
        };
        /**
         * UserPasswordReset
         * @description Password replacement requested by an authorized administrator.
         */
        UserPasswordReset: {
            /** Temporary Password */
            temporary_password: string;
        };
        /**
         * UserProfileUpdate
         * @description Editable profile fields for the authenticated account owner.
         */
        UserProfileUpdate: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
        };
        /**
         * UserRead
         * @description Public user representation.
         */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @description Authorization roles for project and document review workflows.
         * @enum {string}
         */
        UserRole: "ENGINEER" | "LEAD_ENGINEER" | "SUPERUSER";
        /**
         * UserStatusUpdate
         * @description Explicit account activation state update.
         */
        UserStatusUpdate: {
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    change_password_api_v1_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_profile_api_v1_auth_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_engineer_api_v1_auth_register_engineer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterEngineerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_auth_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserManagementRead"][];
                };
            };
        };
    };
    create_user_api_v1_auth_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagedUserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserManagementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_user_password_api_v1_auth_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPasswordReset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserManagementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_status_api_v1_auth_users__user_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserManagementRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dictionary_terms_api_v1_dictionary_terms_get: {
        parameters: {
            query?: {
                scope?: string | null;
                status?: components["schemas"]["DictionaryTermStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryTermListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dictionary_term_api_v1_dictionary_terms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryTermCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryTermRead"];
                };
            };
            /** @description Dictionary term not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Term already exists for the given scope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_dictionary_term_api_v1_dictionary_terms__term_id__approve_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                term_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictionaryTermApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryTermRead"];
                };
            };
            /** @description Dictionary term not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Term already exists for the given scope */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    upload_document_api_v1_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_documents_upload_post"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_document_api_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete_document_api_v1_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_document_events_api_v1_documents__document_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_document_api_v1_documents__document_id__export_get: {
        parameters: {
            query: {
                format: string;
                /** @description Include minor and informational findings. */
                include_minors?: boolean;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_issues_api_v1_documents__document_id__issues_get: {
        parameters: {
            query?: {
                category?: components["schemas"]["IssueCategory"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    mark_document_reviewed_api_v1_documents__document_id__mark_reviewed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_pdf_api_v1_documents__document_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Document or canonical PDF not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_preview_api_v1_documents__document_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewReportPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_document_revision_api_v1_documents__document_id__request_revision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentWorkflowUpdate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_status_api_v1_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    get_traceability_summary_api_v1_documents__document_id__traceability_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceabilitySummaryResponse"];
                };
            };
            /** @description Document not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_document_api_v1_documents__document_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentWorkflowUpdate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    curate_issue_api_v1_issues__issue_id__curation_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueCurationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                user_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_project_api_v1_projects__project_id__assign_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectAssignment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_project_documents_api_v1_projects__project_id__documents_get: {
        parameters: {
            query?: {
                engineer_id?: string | null;
                sort_by?: string;
                status?: components["schemas"]["DocumentStatus"] | null;
                has_blockers?: boolean | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_project_document_api_v1_projects__project_id__documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_project_document_api_v1_projects__project_id__documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_standard_patterns_api_v1_standards_registry_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardPatternListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    create_standard_pattern_api_v1_standards_registry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StandardPatternCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StandardPatternRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Feature not implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
