export type Locale = "en" | "id";
export const LOCALE_STORAGE_KEY = "matqc-locale";

export const DEFAULT_LOCALE: Locale = "en";
const catalog = {
  en: {
    language: "English", languageIndonesian: "Bahasa Indonesia", toggleLanguage: "Switch language",
    projects: "Projects", referenceLibrary: "Reference Library", manageUsers: "Manage Users", accountSettings: "Account settings", changePassword: "Change Password", profile: "Profile", logout: "Logout", authenticated: "Authenticated", workspaceUser: "Workspace user", toggleNavigation: "Toggle navigation",
    personalDetails: "Personal details", personalDetailsHelp: "These details are visible to reviewers and in project metadata.", fullName: "Full name", saveProfile: "Save profile", saving: "Saving...", profileLoadedFor: "Profile loaded for {role}.", profileUpdated: "Profile updated successfully.", loadProfileError: "Could not load profile.", updateProfileError: "Could not update profile.", security: "Security", securityHelp: "Change your workspace password without leaving account settings.", currentPassword: "Current password", newPassword: "New password", confirmNewPassword: "Confirm new password", passwordChanged: "Password changed successfully.", changePasswordError: "Could not change password.", passwordMinLength: "New password must be at least 8 characters.", passwordMismatch: "New password confirmation does not match.",
    loginKicker: "Document assurance platform", loginTitle: "Clarity for every engineering review.", loginDescription: "Keep plant documents, ownership, and lead verification in one calm workspace.", roleAware: "Role-aware project access", secureWorkspace: "Secure workspace", welcomeBack: "Welcome back", signInDescription: "Sign in with your engineering account to continue.", email: "Email", password: "Password", enterPassword: "Enter your password", signIn: "Sign in · Enter workspace", signingIn: "Signing in...", unableSignIn: "Unable to sign in.",
    document: "Document", findings: "Findings", export: "Export", reportPreview: "Review Report Preview", dictionary: "Dictionary", refreshFindings: "Refresh findings", inspection: "Inspection", pages: "pages", totalFindings: "total findings", included: "Included", blockers: "Blockers", reviewCuration: "Review & Curation", layoutFormat: "Layout & Format", budinskiCompliance: "Budinski Compliance", standardsCitations: "Standards & Citations", languageTypos: "Language & Typos", allIssues: "All Issues", total: "total", filterByRule: "Filter by rule, fact, or page number...", filterSeverity: "Filter by Severity", allSeverities: "All Severities", blockerOnly: "Blocker Only", criticalOnly: "Critical Only", majorOnly: "Major Only", minorOnly: "Minor Only", infoOnly: "Info Only",
    failedPipeline: "The review pipeline failed. Findings shown below may be incomplete.", completedWarnings: "Review completed with warnings. Check the findings before exporting.", pipelineRunning: "The review pipeline is still running. Findings may continue to appear.", findingsRefreshed: "Findings successfully refreshed.", reloadFailed: "Failed to reload findings list.", updateCuration: "Finding {id} {action} report.", includedAction: "included in", excludedAction: "excluded from", updateFailed: "Failed to update report curation",
    loadingReport: "Loading report preview...", reportError: "Unable to load report preview.", close: "Close", downloadDocx: "Download DOCX Report", downloadPdf: "Download Annotated PDF", generating: "Generating", ready: "ready", annotatedPdf: "annotated PDF", docxReport: "DOCX report", includeMinors: "Include minor findings", reportLanguage: "Report language", reportLanguageHelp: "DOCX follows this language. Annotated PDF keeps original-source annotations.", cancel: "Cancel", download: "Download", reportSummary: "Report Summary", noSummary: "No summary available.", summaryJudgement: "Summary judgement", sourceText: "Source text", reviewerNote: "Reviewer note", save: "Save", edit: "Edit", page: "Page", original: "Original", suggestion: "Suggestion", errorGeneric: "Something went wrong.",
    statusQueued: "Queued", statusProcessing: "Processing", statusCompleted: "Completed", statusFailed: "Failed", statusCompletedWarnings: "Completed with warnings", roleEngineer: "Engineer", roleLead: "Lead Engineer", roleSuperuser: "Superuser", severityBlocker: "Blocker", severityCritical: "Critical", severityMajor: "Major", severityMinor: "Minor", severityInfo: "Info", severityHigh: "High", severityMedium: "Medium", severityLow: "Low"
  },
  id: {
    language: "English", languageIndonesian: "Bahasa Indonesia", toggleLanguage: "Ganti bahasa",
    projects: "Proyek", referenceLibrary: "Pustaka Referensi", manageUsers: "Kelola Pengguna", accountSettings: "Pengaturan akun", changePassword: "Ubah Kata Sandi", profile: "Profil", logout: "Keluar", authenticated: "Terautentikasi", workspaceUser: "Pengguna ruang kerja", toggleNavigation: "Buka/tutup navigasi",
    personalDetails: "Detail pribadi", personalDetailsHelp: "Detail ini terlihat oleh peninjau dan tercantum dalam metadata proyek.", fullName: "Nama lengkap", saveProfile: "Simpan profil", saving: "Menyimpan...", profileLoadedFor: "Profil dimuat untuk {role}.", profileUpdated: "Profil berhasil diperbarui.", loadProfileError: "Profil tidak dapat dimuat.", updateProfileError: "Profil tidak dapat diperbarui.", security: "Keamanan", securityHelp: "Ubah kata sandi ruang kerja tanpa meninggalkan pengaturan akun.", currentPassword: "Kata sandi saat ini", newPassword: "Kata sandi baru", confirmNewPassword: "Konfirmasi kata sandi baru", passwordChanged: "Kata sandi berhasil diubah.", changePasswordError: "Kata sandi tidak dapat diubah.", passwordMinLength: "Kata sandi baru harus terdiri dari minimal 8 karakter.", passwordMismatch: "Konfirmasi kata sandi baru tidak cocok.",
    loginKicker: "Platform penjaminan dokumen", loginTitle: "Kejelasan untuk setiap tinjauan teknik.", loginDescription: "Simpan dokumen pabrik, kepemilikan, dan verifikasi pimpinan dalam satu ruang kerja.", roleAware: "Akses proyek berbasis peran", secureWorkspace: "Ruang kerja aman", welcomeBack: "Selamat datang kembali", signInDescription: "Masuk dengan akun teknik Anda untuk melanjutkan.", email: "Email", password: "Kata sandi", enterPassword: "Masukkan kata sandi", signIn: "Masuk · Buka ruang kerja", signingIn: "Sedang masuk...", unableSignIn: "Tidak dapat masuk.",
    document: "Dokumen", findings: "Temuan", export: "Ekspor", reportPreview: "Pratinjau Laporan", dictionary: "Kamus", refreshFindings: "Segarkan temuan", inspection: "Inspeksi", pages: "halaman", totalFindings: "total temuan", included: "Disertakan", blockers: "Penghambat", reviewCuration: "Tinjauan & Kurasi", layoutFormat: "Tata Letak & Format", budinskiCompliance: "Kepatuhan Budinski", standardsCitations: "Standar & Kutipan", languageTypos: "Bahasa & Salah Ketik", allIssues: "Semua Isu", total: "total", filterByRule: "Filter berdasarkan aturan, fakta, atau nomor halaman...", filterSeverity: "Filter berdasarkan Tingkat Keparahan", allSeverities: "Semua Tingkat Keparahan", blockerOnly: "Hanya Penghambat", criticalOnly: "Hanya Kritis", majorOnly: "Hanya Mayor", minorOnly: "Hanya Minor", infoOnly: "Hanya Info", legacyHigh: "Hanya High Lama", legacyMedium: "Hanya Medium Lama", legacyLow: "Hanya Low Lama", filterStatus: "Filter berdasarkan Status Laporan", allStatuses: "Semua Status Laporan", includedInReport: "Disertakan dalam Laporan", excludedFromReport: "Dikecualikan dari Laporan", loadingFindings: "Memuat temuan dokumen...", noMatch: "Tidak ada temuan yang cocok dengan filter", clearFilters: "Coba hapus filter atau istilah pencarian.", showing: "Menampilkan", of: "dari", includedLower: "disertakan",
    failedPipeline: "Alur tinjauan gagal. Temuan di bawah mungkin tidak lengkap.", completedWarnings: "Tinjauan selesai dengan peringatan. Periksa temuan sebelum mengekspor.", pipelineRunning: "Alur tinjauan masih berjalan. Temuan dapat terus muncul.", findingsRefreshed: "Temuan berhasil disegarkan.", reloadFailed: "Gagal memuat ulang daftar temuan.", updateCuration: "Temuan {id} {action} laporan.", includedAction: "disertakan dalam", excludedAction: "dikecualikan dari", updateFailed: "Gagal memperbarui kurasi laporan",
    loadingReport: "Memuat pratinjau laporan...", reportError: "Tidak dapat memuat pratinjau laporan.", close: "Tutup", downloadDocx: "Unduh DOCX", downloadPdf: "Unduh PDF", generating: "Membuat", ready: "siap", annotatedPdf: "PDF beranotasi", docxReport: "laporan DOCX", includeMinors: "Sertakan temuan minor", reportLanguage: "Bahasa laporan", reportLanguageHelp: "DOCX mengikuti bahasa ini. PDF beranotasi mempertahankan anotasi dari sumber.", cancel: "Batal", download: "Unduh", reportSummary: "Ringkasan Laporan", noSummary: "Ringkasan tidak tersedia.", summaryJudgement: "Penilaian ringkasan", sourceText: "Teks sumber", reviewerNote: "Catatan peninjau", save: "Simpan", edit: "Edit", page: "Halaman", original: "Asli", suggestion: "Saran", errorGeneric: "Terjadi kesalahan.",
    statusQueued: "Antrean", statusProcessing: "Memproses", statusCompleted: "Selesai", statusFailed: "Gagal", statusCompletedWarnings: "Selesai dengan peringatan", roleEngineer: "Insinyur", roleLead: "Insinyur Pimpinan", roleSuperuser: "Superuser", severityBlocker: "Penghambat", severityCritical: "Kritis", severityMajor: "Mayor", severityMinor: "Minor", severityInfo: "Info", severityHigh: "High", severityMedium: "Medium", severityLow: "Low"
  }
} as const;
export type TranslationKey = keyof typeof catalog.en;
export function normalizeLocale(value: string | null | undefined): Locale { return value?.toLowerCase().startsWith("id") ? "id" : "en"; }
export function detectLocale(): Locale { return typeof navigator !== "undefined" ? normalizeLocale(navigator.language) : "en"; }
export function translate(locale: Locale, key: TranslationKey, vars?: Record<string, string | number>): string {
  const value: string = catalog[locale][key] ?? catalog.en[key];
  return Object.entries(vars ?? {}).reduce((result, [name, replacement]) => result.replaceAll(`{${name}}`, String(replacement)), value);
}
export const messages = catalog;
